name: Azure Web App

on:
  push:
    branches:
      - Dev

jobs:
  build_deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy
    environment:
      name: "Production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0.x"
          dotnet-quality: preview

      - name: Build with dotnet
        run: dotnet publish SoarCraft.AwaiShop/SoarCraft.AwaiShop.csproj -c Release -o ${{env.DOTNET_ROOT}}/myapp

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: "Awai"
          slot-name: "Production"
          package: ${{env.DOTNET_ROOT}}/myapp
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_C99EA4B4F77A41508E090AF728BF173A }}
